//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave
    {
        public int LeaveId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string StartDuration { get; set; }
        public string EndDuration { get; set; }
        public string Reason { get; set; }
        public string ResponseComment { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> IsDeleted { get; set; }
    
        public virtual User User { get; set; }
    }
}
