//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task10.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ExamEntities : DbContext
    {
        public ExamEntities()
            : base("name=ExamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dish> Dishes { get; set; }
        public virtual DbSet<DishItem> DishItems { get; set; }
        public virtual DbSet<OrderItem> OrderItems { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<CartItemId> CartItemIds { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<EventItem> EventItems { get; set; }
        public virtual DbSet<OrderRefund> OrderRefunds { get; set; }
        public virtual DbSet<Overtime> Overtimes { get; set; }
        public virtual DbSet<Leave> Leaves { get; set; }
        public virtual DbSet<CookingSession> CookingSessions { get; set; }
        public virtual DbSet<CookingSessionAttendee> CookingSessionAttendees { get; set; }
        public virtual DbSet<DineInTable> DineInTables { get; set; }
        public virtual DbSet<ReservedTable> ReservedTables { get; set; }
    
        public virtual ObjectResult<sp_orderDetails_Result> sp_orderDetails(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_orderDetails_Result>("sp_orderDetails", idParameter);
        }
    
        public virtual ObjectResult<sp_orderRefund_Result> sp_orderRefund(Nullable<int> id, Nullable<int> isDelete)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var isDeleteParameter = isDelete.HasValue ?
                new ObjectParameter("IsDelete", isDelete) :
                new ObjectParameter("IsDelete", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_orderRefund_Result>("sp_orderRefund", idParameter, isDeleteParameter);
        }
    
        public virtual ObjectResult<new_get_notReserved_Table_forBooking_Result> new_get_notReserved_Table_forBooking(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<int> noofPeoples)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("fromDate", fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("toDate", toDate) :
                new ObjectParameter("toDate", typeof(System.DateTime));
    
            var noofPeoplesParameter = noofPeoples.HasValue ?
                new ObjectParameter("noofPeoples", noofPeoples) :
                new ObjectParameter("noofPeoples", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<new_get_notReserved_Table_forBooking_Result>("new_get_notReserved_Table_forBooking", fromDateParameter, toDateParameter, noofPeoplesParameter);
        }
    }
}
