//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderRefund
    {
        public int OrderRefundId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> OrderItemId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> RefundDate { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> IsDeleted { get; set; }
    
        public virtual OrderItem OrderItem { get; set; }
        public virtual Order Order { get; set; }
    }
}
